/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessLayoutARouteImport } from './routes/_pathlessLayout/a'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppDashboardRouteImport } from './routes/_auth/app/dashboard'
import { Route as AuthAppUsersUserIdRouteRouteImport } from './routes/_auth/app/users/$userId/route'
import { Route as AuthAppUsersUserIdIndexRouteImport } from './routes/_auth/app/users/$userId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutARoute = PathlessLayoutARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppDashboardRoute = AuthAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppUsersUserIdRouteRoute = AuthAppUsersUserIdRouteRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppUsersUserIdIndexRoute = AuthAppUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppUsersUserIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/a': typeof PathlessLayoutARoute
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/users/$userId': typeof AuthAppUsersUserIdRouteRouteWithChildren
  '/app/users/$userId/': typeof AuthAppUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/a': typeof PathlessLayoutARoute
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/users/$userId': typeof AuthAppUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_pathlessLayout/a': typeof PathlessLayoutARoute
  '/_auth/app/dashboard': typeof AuthAppDashboardRoute
  '/_auth/app/users/$userId': typeof AuthAppUsersUserIdRouteRouteWithChildren
  '/_auth/app/users/$userId/': typeof AuthAppUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/app'
    | '/a'
    | '/app/dashboard'
    | '/app/users/$userId'
    | '/app/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/app'
    | '/a'
    | '/app/dashboard'
    | '/app/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_pathlessLayout'
    | '/about'
    | '/login'
    | '/_auth/app'
    | '/_pathlessLayout/a'
    | '/_auth/app/dashboard'
    | '/_auth/app/users/$userId'
    | '/_auth/app/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/a': {
      id: '/_pathlessLayout/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof PathlessLayoutARouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/dashboard': {
      id: '/_auth/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/users/$userId': {
      id: '/_auth/app/users/$userId'
      path: '/users/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof AuthAppUsersUserIdRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/users/$userId/': {
      id: '/_auth/app/users/$userId/'
      path: '/'
      fullPath: '/app/users/$userId/'
      preLoaderRoute: typeof AuthAppUsersUserIdIndexRouteImport
      parentRoute: typeof AuthAppUsersUserIdRouteRoute
    }
  }
}

interface AuthAppUsersUserIdRouteRouteChildren {
  AuthAppUsersUserIdIndexRoute: typeof AuthAppUsersUserIdIndexRoute
}

const AuthAppUsersUserIdRouteRouteChildren: AuthAppUsersUserIdRouteRouteChildren =
  {
    AuthAppUsersUserIdIndexRoute: AuthAppUsersUserIdIndexRoute,
  }

const AuthAppUsersUserIdRouteRouteWithChildren =
  AuthAppUsersUserIdRouteRoute._addFileChildren(
    AuthAppUsersUserIdRouteRouteChildren,
  )

interface AuthAppRouteRouteChildren {
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppUsersUserIdRouteRoute: typeof AuthAppUsersUserIdRouteRouteWithChildren
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppUsersUserIdRouteRoute: AuthAppUsersUserIdRouteRouteWithChildren,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutARoute: typeof PathlessLayoutARoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutARoute: PathlessLayoutARoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
